# Build stage
FROM node:25-alpine AS builder
RUN npm install -g pnpm
WORKDIR /app
COPY . .

ENV CI=true
RUN pnpm install --frozen-lockfile
RUN pnpm run build:web

# Serve stage
FROM nginx:alpine
COPY --from=builder /app/packages/frontend/web/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]