
include:
  - path: docker-compose.base.yml
    project_directory: docker

name: hostchatlive

services:
  api:
    container_name: api-backend
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "3000:3000"

    environment:
      MONGODB_URI: ${MONGODB_URI}    
    networks:
      - hostchatnetwork
        

networks:
  hostchatnetwork:
    driver: bridge


